# Generated by Django 6.0.3 on 2026-04-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvitation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
