databases:
  - name: gestion-taches-db
    plan: starter
    databaseName: gestion_taches
    user: gestion_taches_user

services:
  - type: web
    name: gestion-taches-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: starter
    healthCheckPath: /api/docs/
    envVars:
      - key: DJANGO_ENV
        value: prod
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: USE_REDIS
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-taches-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: MAGIC_LINK_MAX_AGE_SECONDS
        value: "900"
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "true"
      - key: EMAIL_USE_SSL
        value: "false"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: REDIS_URL
        sync: false
