# Generated by Django 6.0.3 on 2026-04-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
        ('task', '0004_alter_task_options_task_position'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_column_name_per_project'),
        ),
    ]
