# Generated by Django 6.0.3 on 2026-03-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('member', 'Membre'), ('reader', 'Lecteur')], default='reader', max_length=10),
        ),
    ]
